CRM TripleTech/CRM TripleTech/Models/Entities/PURCHASEORDER.cs
namespace CRM_TripleTech.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("PURCHASEORDER")]
    public partial class PURCHASEORDER
    {
        public int ID { get; set; }

        [StringLength(50)]
        public string PURCHASENO { get; set; }

        [ForeignKey("COMPANY")]
        public int COMPANY_ID { get; set; }

        [ForeignKey("INVENTORY")]
        public int INVENTORY_ID { get; set; }

        public int QUANTITY { get; set; }

        public double AMOUNT { get; set; }

        public DateTime? DATEPURCHASED { get; set; }

        [ForeignKey("USER")]
        public int BUYER_ID {get;set;}

        public DateTime? DATEUPDATED { get; set; }

        public string STATUS { get; set; }

        public int LASTUPDATEDBY { get; set; }

        public virtual USER USER { get; set; }
        public virtual COMPANY COMPANY { get; set; }
        public virtual INVENTORY INVENTORY { get; set; }

    }
}

CRM TripleTech/CRM TripleTech/Models/ViewModels/PurchaseOrder/PurchaseOrderViewModel.cs
using CRM_TripleTech.Models.Entities;
using System.Collections.Generic;
using System.Web.Mvc;

namespace CRM_TripleTech.Models.ViewModels.PurchaseOrder
{
    public class PurchaseOrderViewModel
    {
        //public string PurchaseOrderID { get; set; }
        //public string VendorCode { get; set; }
        //public string CompanyName { get; set; }
        //public string Quantity { get; set; }
        //public string DateOrdered { get; set; }
        //public string Amount { get; set; }

        public string ID { get; set; }
        public string CompanyID { get; set; }
        public List<SelectListItem> lst_Company { get; set; }  

        public List<PURCHASEORDER> lst_Main { get; set; }
    }
}

CRM TripleTech/CRM TripleTech/Controllers/PurchaseOrderController.cs
using Autofac;
using CRM_TripleTech.Models;
using CRM_TripleTech.Models.DAL;
using CRM_TripleTech.Models.Interface;
using CRM_TripleTech.Models.ViewModels.PurchaseOrder;
using System;
using System.Linq;
using System.Web.Mvc;

namespace CRM_TripleTech.Controllers
{
    public class PurchaseOrderController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public PurchaseOrderController()
        {
            var container = ContainerConfig.Configure();
            var scope = container.BeginLifetimeScope();
            unitOfWork = scope.Resolve<IUnitOfWork>();
        }

        // GET: PurchaseOrder
        public ActionResult Index(PurchaseOrderViewModel model)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            model.lst_Main = unitOfWork.PurchaseOrder.getEntitites(model, m => m.STATUS == Constant.PURCHASE_ORDER_STATUS_PROCESSING).ToList();

            model.lst_Company = unitOfWork.Company.Find(m => m.TYPE == Constant.COMPANY_TYPE_VENDOR).Select(m => new SelectListItem
            {
                Text = m.NAME,
                Value = m.ID.ToString()
            }).ToList();

            return View(model);
        }

        public ActionResult UpdateStatus(int id, string transaction)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            var purchaseorder = unitOfWork.PurchaseOrder.Get(id);
            string value = string.Empty;

            switch (transaction)
            {
                case Constant.PURCHASE_ORDER_STATUS_RECEIVED:
                    purchaseorder.STATUS = Constant.PURCHASE_ORDER_STATUS_RECEIVED;

                    unitOfWork.PurchaseOrder.Update(purchaseorder);

                    var inventory = unitOfWork.Inventory.Get(purchaseorder.INVENTORY_ID);

                    inventory.QUANTITY += purchaseorder.QUANTITY;
                    inventory.LASTUPDATEDBY = StaticMethods.TryParseObjToInt(Session["UserID"]).Value;
                    inventory.DATEUPDATED = DateTime.UtcNow;

                    unitOfWork.Inventory.Update(inventory);

                    unitOfWork.SaveChanges();
                    break;
            }

            return RedirectToAction("Index");
        }
    }
}

CRM TripleTech/CRM TripleTech/Views/PurchaseOrder/Index.cshtml
@model CRM_TripleTech.Models.ViewModels.PurchaseOrder.PurchaseOrderViewModel
@using CRM_TripleTech.Models
@{
    ViewBag.Title = "Purchase Order";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="title">Search Filter</h4>
                <p class="category">Minimize selection of records by selecting a value</p>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Index", "PurchaseOrder"))
                {
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-floating">ID</label>
                                @Html.TextBoxFor(m => m.ID, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-floating">Company</label>
                                @Html.DropDownListFor(m => m.CompanyID, Model.lst_Company, "-- Select an item --", htmlAttributes: new { @class = "form-control" })
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">
                                Search
                                <div class="ripple-container"></div>
                            </button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Purchase Order Table</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tblMain" class="table table-hover">
                        <thead class="text-primary">
                            <tr>
                                <th></th>
                                <th>ID</th>
                                <th>Purchase No</th>
                                <th>Company</th>
                                <th>Inventory</th>
                                <th>Quantity</th>
                                <th>Total Price</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lst_Main)
                            {
                                <tr>
                                    <td></td>
                                    <td>@item.ID</td>
                                    <td>
                                        @item.PURCHASENO
                                    </td>
                                    <td>
                                        @if (item.COMPANY != null)
                                        {
                                            @item.COMPANY.CODE
                                            <br />
                                            <small>@item.COMPANY.NAME</small>
                                        }
                                    </td>
                                    <td>
                                        @if (item.INVENTORY != null)
                                        {
                                            @item.INVENTORY.NAME
                                            if (item.INVENTORY.CATEGORY != null)
                                            {
                                                <br />
                                                <small>@item.INVENTORY.CATEGORY.NAME</small>
                                            }
                                        }
                                    </td>
                                    <td>@item.QUANTITY</td>
                                    <td>₱ @item.AMOUNT</td>
                                    <td>
                                        @if (item.STATUS == Constant.PURCHASE_ORDER_STATUS_PROCESSING)
                                        {<span class="text-info">@item.STATUS</span> }
                                        else if (item.STATUS == Constant.PURCHASE_ORDER_STATUS_RECEIVED)
                                        { <span class="text-success">@item.STATUS</span> }
                                    </td>
                                    <td class="td-actions">
                                        <a href="@Url.Action("UpdateStatus", "PurchaseOrder", routeValues: new { @id = item.ID, @transaction = Constant.PURCHASE_ORDER_STATUS_RECEIVED})" rel="tooltip" class="btn btn-info">
                                            <i class="material-icons"></i> COMPLETE
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script>
        $(document).ready(function () {
            $('#tblMain').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': false,
                'autoWidth': true
            });
        });
    </script>
}