CRM TripleTech/CRM TripleTech/Controllers/OrderTranController.cs
using Autofac;
using CRM_TripleTech.Models;
using CRM_TripleTech.Models.DAL;
using CRM_TripleTech.Models.Entities;
using CRM_TripleTech.Models.Interface;
using CRM_TripleTech.Models.ViewModels.OrderTran;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CRM_TripleTech.Controllers
{
    public class OrderTranController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public OrderTranController()
        {
            var container = ContainerConfig.Configure();
            var scope = container.BeginLifetimeScope();
            unitOfWork = scope.Resolve<IUnitOfWork>();
        }

        // GET: OrderTran
        public ActionResult Index(OrderTranViewModel model)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            //var ordertransactions = unitOfWork.OrderTran.getForTransactionEntities(model)
            //    .OrderByDescending(m => m.ID)
            //    .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_LOW)
            //    .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_MED)
            //    .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_HIGH)
            //    .ToList();

            var ordertransactions = unitOfWork.OrderTran.getForTransactionEntities(model)
                .OrderBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_LOW)
                .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_MED)
                .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_HIGH)
                .ThenByDescending(m => m.ID);

            model.lst_Main = new List<OrderTranModel>();
            foreach (var item in ordertransactions)
            {
                model.lst_Main.Add(new OrderTranModel
                {
                    Id = item.ID,
                    CustomerName = item.USER.FIRSTNAME + " " + item.USER.LASTNAME,
                    Company = item.USER.COMPANY_ID != 0 ? item.USER.COMPANY.NAME : string.Empty,
                    PriorityLevel = item.PRIORITYLEVEL,
                    Location = item.LOCATION,
                    Status = item.STATUS,
                    TotalPrice = item.TOTALPRICE
                });
            }

            model.drp_Status = new List<SelectListItem>();

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_ACTIVE,
                Value = Constant.ORDERTRAN_STATUS_ACTIVE
            });

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_PROCESSING,
                Value = Constant.ORDERTRAN_STATUS_PROCESSING
            });

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_SHIPPING,
                Value = Constant.ORDERTRAN_STATUS_SHIPPING
            });

            return View(model);
        }

        public ActionResult Details(int? id)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            if (!id.HasValue || id.Value == Constant.NO_ORDERTRAN_ID) return RedirectToAction("Index");

            OrderTranModel model = new OrderTranModel();

            var ordertran = unitOfWork.OrderTran.Get(id.Value);

            model.Id = ordertran.ID;
            model.CustomerName = ordertran.USER.FIRSTNAME + " " + ordertran.USER.LASTNAME;
            model.Company = ordertran.USER.COMPANY_ID != 0 ? ordertran.USER.COMPANY.NAME : string.Empty;
            model.PriorityLevel = ordertran.PRIORITYLEVEL;
            model.Location = ordertran.LOCATION;
            model.Status = ordertran.STATUS;
            model.TotalPrice = ordertran.TOTALPRICE;

            model.DateDelivered = ordertran.DATEDELIVERED;
            model.DateUpdated = ordertran.DATEUPDATED;

            var user = unitOfWork.User.Get(ordertran.LASTUPDATEDBY);
            model.LastUpdatedBy = user != null ? user.FIRSTNAME + " " + user.LASTNAME : string.Empty;

            model.lst_Main = new List<OrderTranDetailModel>();

            var lst_ordertrandetail = ordertran.ORDERTRANDETAIL.ToList();
            foreach (var item in lst_ordertrandetail)
            {
                var price = item.PRICE / item.QUANTITY;

                model.lst_Main.Add(new OrderTranDetailModel
                {
                    Id = item.ID,
                    CategoryName = item.INVENTORY.CATEGORY.NAME,
                    Name = item.INVENTORY.NAME,
                    Price = price,
                    Quantity = item.QUANTITY,
                    Amount = item.PRICE,
                    Status = item.STATUS
                });
            }

            return View(model);
        }

        public ActionResult UpdateStatus(int id, string transaction)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            var ordertran = unitOfWork.OrderTran.Get(id);
            var ordertrandetails = new List<ORDERTRANDETAIL>();
            string value = string.Empty;

            switch (transaction)
            {
                case Constant.ORDERTRAN_TRANSACTION_TYPE_SHIP:
                    ordertran.STATUS = Constant.ORDERTRAN_STATUS_SHIPPING;
                    ordertrandetails = ordertran.ORDERTRANDETAIL.Where(m => m.STATUS != Constant.ORDERTRAN_STATUS_CANCELLED).ToList();
                    value = Constant.ORDERTRAN_STATUS_SHIPPING;
                    break;
                case Constant.ORDERTRAN_TRANSACTION_TYPE_COMPLETE:
                    ordertran.DATEDELIVERED = DateTime.UtcNow;
                    ordertran.STATUS = Constant.ORDERTRAN_STATUS_COMPLETED;
                    ordertrandetails = ordertran.ORDERTRANDETAIL.Where(m => m.STATUS != Constant.ORDERTRAN_STATUS_CANCELLED).ToList();
                    value = Constant.ORDERTRAN_STATUS_COMPLETED;
                    break;
                case Constant.ORDERTRAN_TRANSACTION_TYPE_CANCEL:
                    ordertran.STATUS = Constant.ORDERTRAN_STATUS_CANCELLED;
                    ordertrandetails = ordertran.ORDERTRANDETAIL.Where(m => m.STATUS != Constant.ORDERTRAN_STATUS_CANCELLED).ToList();
                    value = Constant.ORDERTRAN_STATUS_CANCELLED;
                    break;
            }

            ordertran.LASTUPDATEDBY = StaticMethods.TryParseObjToInt(Session["UserID"]).Value;
            ordertran.DATEUPDATED = DateTime.UtcNow;

            foreach (var item in ordertrandetails)
            {
                item.STATUS = value;
                item.LASTUPDATEDBY = StaticMethods.TryParseObjToInt(Session["UserID"]).Value;
                item.DATEUPDATED = DateTime.UtcNow;

                unitOfWork.OrderTranDetail.Update(item);
            }

            unitOfWork.OrderTran.Update(ordertran);

            unitOfWork.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

CRM TripleTech/CRM TripleTech/Controllers/OrderTranPriorityController.cs
using CRM_TripleTech.Models.DAL;
using CRM_TripleTech.Models;
using CRM_TripleTech.Models.Entities;
using CRM_TripleTech.Models.ViewModels.OrderTran;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Autofac;
using CRM_TripleTech.Models.Interface;

namespace CRM_TripleTech.Controllers
{
    public class OrderTranPriorityController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public OrderTranPriorityController()
        {
            var container = ContainerConfig.Configure();
            var scope = container.BeginLifetimeScope();
            unitOfWork = scope.Resolve<IUnitOfWork>();
        }
        // GET: OrderTranPriority
        public ActionResult Index(OrderTranViewModel model)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            var ordertransactions = unitOfWork.OrderTran.getActiveEntities(model);

            model.lst_Main = new List<OrderTranModel>();
            foreach (var item in ordertransactions)
            {
                model.lst_Main.Add(new OrderTranModel
                {
                    Id = item.ID,
                    CustomerName = item.USER.FIRSTNAME + " " + item.USER.LASTNAME,
                    Company = item.USER.COMPANY_ID != 0 ? item.USER.COMPANY.NAME : string.Empty,
                    PriorityLevel = item.PRIORITYLEVEL,
                    Location = item.LOCATION,
                    Status = item.STATUS,
                    TotalPrice = item.TOTALPRICE
                });
            }

            model.drp_Status = new List<SelectListItem>();

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_ACTIVE,
                Value = Constant.ORDERTRAN_STATUS_ACTIVE
            });

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_PROCESSING,
                Value = Constant.ORDERTRAN_STATUS_PROCESSING
            });

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_SHIPPING,
                Value = Constant.ORDERTRAN_STATUS_SHIPPING
            });

            return View(model);
        }

        public ActionResult UpdateStatus(int id, string transaction)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            var ordertran = unitOfWork.OrderTran.Get(id);

            switch (transaction)
            {
                case Constant.PRIORITY_LEVEL_HIGH:
                    ordertran.PRIORITYLEVEL = Constant.PRIORITY_LEVEL_HIGH;
                    break;
                case Constant.PRIORITY_LEVEL_MED:
                    ordertran.PRIORITYLEVEL = Constant.PRIORITY_LEVEL_MED;
                    break;
                case Constant.PRIORITY_LEVEL_LOW:
                    ordertran.PRIORITYLEVEL = Constant.PRIORITY_LEVEL_LOW;
                    break;
            }

            unitOfWork.OrderTran.Update(ordertran);
            unitOfWork.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

CRM TripleTech/CRM TripleTech/Views/OrderTranPriority/Index.cshtml
@model CRM_TripleTech.Models.ViewModels.OrderTran.OrderTranViewModel
@using CRM_TripleTech.Models
@{
    ViewBag.Title = "Order Priority";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="title">Search Filter</h4>
                <p class="category">Minimize selection of records by selecting a value</p>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("Index", "OrderTranPriority"))
                {
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-floating">ID</label>
                                @Html.TextBoxFor(m => m.ID, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group bmd-form-group">
                                <label class="bmd-label-floating">Status</label>
                                @Html.DropDownListFor(m => m.Status, Model.drp_Status, "-- Select an item --", htmlAttributes: new { @class = "form-control" })
                            </div>
                            <button type="submit" class="btn btn-primary pull-right">
                                Search
                                <div class="ripple-container"></div>
                            </button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Orders Table</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tblMain" class="table table-hover">
                        <thead class="text-primary">
                            <tr>
                                <th></th>
                                <th>ID</th>
                                <th>Customer</th>
                                <th>Priority</th>
                                <th>Location</th>
                                <th>Status</th>
                                <th>Total Price</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lst_Main)
                            {
                                <tr>
                                    <td></td>
                                    <td><a href="@Url.Action("Details", "OrderTran", routeValues: new { @id = item.Id})">@item.Id</a></td>
                                    <td>
                                        @item.CustomerName
                                        <br />
                                        <small>@item.Company</small>
                                    </td>
                                    <td>
                                        @if (item.PriorityLevel == Constant.PRIORITY_LEVEL_HIGH)
                                        {<span class="text-danger">@item.PriorityLevel</span> }
                                    else if (item.PriorityLevel == Constant.PRIORITY_LEVEL_MED)
                                    { <span class="text-warning">@item.PriorityLevel</span> }
                                else
                                { <span class="text-success">@item.PriorityLevel</span>}
                                    </td>
                                    <td>@item.Location</td>
                                    <td>
                                        @if (item.Status == Constant.ORDERTRAN_STATUS_ACTIVE)
                                        {<span class="badge badge-pill badge-secondary">@item.Status</span> }
                                    else if (item.Status == Constant.ORDERTRAN_STATUS_PROCESSING)
                                    { <span class="badge badge-pill badge-info">@item.Status</span> }
                                else if (item.Status == Constant.ORDERTRAN_STATUS_SHIPPING)
                                { <span class="badge badge-pill badge-success">@item.Status</span>}
                                    </td>
                                    <td>₱ @item.TotalPrice</td>
                                    <td class="td-actions">
                                        <a href="@Url.Action("UpdateStatus", "OrderTranPriority", routeValues: new { @id = item.Id, @transaction = Constant.PRIORITY_LEVEL_HIGH})" class="btn btn-danger">
                                            <i class="material-icons"></i> HIGH
                                        </a>
                                        <br />
                                        <a href="@Url.Action("UpdateStatus", "OrderTranPriority", routeValues: new { @id = item.Id, @transaction = Constant.PRIORITY_LEVEL_MED})" class="btn btn-warning">
                                            <i class="material-icons"></i> MEDIUM
                                        </a>
                                        <br />
                                        <a href="@Url.Action("UpdateStatus", "OrderTranPriority", routeValues: new { @id = item.Id, @transaction = Constant.PRIORITY_LEVEL_LOW})" class="btn btn-success">
                                            <i class="material-icons"></i> LOW
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $('#tblMain').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': false,
                'autoWidth': true
            });
        });
    </script>
}