CRM TripleTech/CRM TripleTech/Models/ViewModels/Report/InventoryReportViewModel.cs
namespace CRM_TripleTech.Models.ViewModels.Report
{
    public class InventoryReportViewModel
    {
        public string InventoryID { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string StockQuantity { get; set; }
        public string ShippedQuantity { get; set; }
        public string SoldQuantity { get; set; }
        public string TotalCost { get; set; }
    }
}

CRM TripleTech/CRM TripleTech/Controllers/OrderTranController.cs
using Autofac;
using CRM_TripleTech.Models;
using CRM_TripleTech.Models.DAL;
using CRM_TripleTech.Models.Entities;
using CRM_TripleTech.Models.Interface;
using CRM_TripleTech.Models.ViewModels.OrderTran;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace CRM_TripleTech.Controllers
{
    public class OrderTranController : Controller
    {
        private readonly IUnitOfWork unitOfWork;

        public OrderTranController()
        {
            var container = ContainerConfig.Configure();
            var scope = container.BeginLifetimeScope();
            unitOfWork = scope.Resolve<IUnitOfWork>();
        }

        // GET: OrderTran
        public ActionResult Index(OrderTranViewModel model)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            //var ordertransactions = unitOfWork.OrderTran.getForTransactionEntities(model)
            //    .OrderByDescending(m => m.ID)
            //    .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_LOW)
            //    .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_MED)
            //    .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_HIGH)
            //    .ToList();

            var ordertransactions = unitOfWork.OrderTran.getForTransactionEntities(model)
                .OrderBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_LOW)
                .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_MED)
                .ThenBy(m => m.PRIORITYLEVEL == Constant.PRIORITY_LEVEL_HIGH)
                .ThenByDescending(m => m.ID);

            model.lst_Main = new List<OrderTranModel>();
            foreach (var item in ordertransactions)
            {
                model.lst_Main.Add(new OrderTranModel
                {
                    Id = item.ID,
                    CustomerName = item.USER.FIRSTNAME + " " + item.USER.LASTNAME,
                    Company = item.USER.COMPANY_ID != 0 ? item.USER.COMPANY.NAME : string.Empty,
                    PriorityLevel = item.PRIORITYLEVEL,
                    Location = item.LOCATION,
                    Status = item.STATUS,
                    TotalPrice = item.TOTALPRICE
                });
            }

            model.drp_Status = new List<SelectListItem>();

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_ACTIVE,
                Value = Constant.ORDERTRAN_STATUS_ACTIVE
            });

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_PROCESSING,
                Value = Constant.ORDERTRAN_STATUS_PROCESSING
            });

            model.drp_Status.Add(new SelectListItem
            {
                Text = Constant.ORDERTRAN_STATUS_SHIPPING,
                Value = Constant.ORDERTRAN_STATUS_SHIPPING
            });

            return View(model);
        }

        public ActionResult Details(int? id)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            if (!id.HasValue || id.Value == Constant.NO_ORDERTRAN_ID) return RedirectToAction("Index");

            OrderTranModel model = new OrderTranModel();

            var ordertran = unitOfWork.OrderTran.Get(id.Value);

            model.Id = ordertran.ID;
            model.CustomerName = ordertran.USER.FIRSTNAME + " " + ordertran.USER.LASTNAME;
            model.Company = ordertran.USER.COMPANY_ID != 0 ? ordertran.USER.COMPANY.NAME : string.Empty;
            model.PriorityLevel = ordertran.PRIORITYLEVEL;
            model.Location = ordertran.LOCATION;
            model.Status = ordertran.STATUS;
            model.TotalPrice = ordertran.TOTALPRICE;

            model.DateDelivered = ordertran.DATEDELIVERED;
            model.DateUpdated = ordertran.DATEUPDATED;

            var user = unitOfWork.User.Get(ordertran.LASTUPDATEDBY);
            model.LastUpdatedBy = user != null ? user.FIRSTNAME + " " + user.LASTNAME : string.Empty;

            model.lst_Main = new List<OrderTranDetailModel>();

            var lst_ordertrandetail = ordertran.ORDERTRANDETAIL.ToList();
            foreach (var item in lst_ordertrandetail)
            {
                var price = item.PRICE / item.QUANTITY;

                model.lst_Main.Add(new OrderTranDetailModel
                {
                    Id = item.ID,
                    CategoryName = item.INVENTORY.CATEGORY.NAME,
                    Name = item.INVENTORY.NAME,
                    Price = price,
                    Quantity = item.QUANTITY,
                    Amount = item.PRICE,
                    Status = item.STATUS
                });
            }

            return View(model);
        }

        public ActionResult UpdateStatus(int id, string transaction)
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            var ordertran = unitOfWork.OrderTran.Get(id);
            var ordertrandetails = new List<ORDERTRANDETAIL>();
            string value = string.Empty;

            switch (transaction)
            {
                case Constant.ORDERTRAN_TRANSACTION_TYPE_SHIP:
                    ordertran.STATUS = Constant.ORDERTRAN_STATUS_SHIPPING;
                    ordertrandetails = ordertran.ORDERTRANDETAIL.Where(m => m.STATUS != Constant.ORDERTRAN_STATUS_CANCELLED).ToList();
                    value = Constant.ORDERTRAN_STATUS_SHIPPING;
                    break;
                case Constant.ORDERTRAN_TRANSACTION_TYPE_COMPLETE:
                    ordertran.DATEDELIVERED = DateTime.UtcNow;
                    ordertran.STATUS = Constant.ORDERTRAN_STATUS_COMPLETED;
                    ordertrandetails = ordertran.ORDERTRANDETAIL.Where(m => m.STATUS != Constant.ORDERTRAN_STATUS_CANCELLED).ToList();
                    value = Constant.ORDERTRAN_STATUS_COMPLETED;
                    break;
                case Constant.ORDERTRAN_TRANSACTION_TYPE_CANCEL:
                    ordertran.STATUS = Constant.ORDERTRAN_STATUS_CANCELLED;
                    ordertrandetails = ordertran.ORDERTRANDETAIL.Where(m => m.STATUS != Constant.ORDERTRAN_STATUS_CANCELLED).ToList();
                    value = Constant.ORDERTRAN_STATUS_CANCELLED;
                    break;
            }

            ordertran.LASTUPDATEDBY = StaticMethods.TryParseObjToInt(Session["UserID"]).Value;
            ordertran.DATEUPDATED = DateTime.UtcNow;

            foreach (var item in ordertrandetails)
            {
                item.STATUS = value;
                item.LASTUPDATEDBY = StaticMethods.TryParseObjToInt(Session["UserID"]).Value;
                item.DATEUPDATED = DateTime.UtcNow;

                unitOfWork.OrderTranDetail.Update(item);
            }

            unitOfWork.OrderTran.Update(ordertran);

            unitOfWork.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

CRM TripleTech/CRM TripleTech/Controllers/ReportsController.cs
using Autofac;
using CRM_TripleTech.Models;
using CRM_TripleTech.Models.DAL;
using CRM_TripleTech.Models.Interface;
using CRM_TripleTech.Models.ViewModels.Report;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace CRM_TripleTech.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        
        public ReportsController()
        {
            var container = ContainerConfig.Configure();
            var scope = container.BeginLifetimeScope();
            unitOfWork = scope.Resolve<IUnitOfWork>();
        }
        // GET: Reports
        public ActionResult PurchaseOrder()
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            List<PurchaseOrderReportViewModel> model = getPurchaseOrder();
            return View(model);
        }

        public ActionResult SalesOrder()
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            List<SalesOrderReportViewModel> model = getSalesOrder();

            return View(model);
        }

        public ActionResult StatementOfAccount()
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            List<OrderListStatementOfAccReportViewModel> model = GetStatementOfAccList();

            return View(model);
        }

        public ActionResult SupplierList()
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            List<SupplierReportViewModel> model = GetSupplierList();

            return View(model);
        }

        public ActionResult InventorySummary()
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            List<InventoryReportViewModel> model = GetInventorySummary();

            return View(model);
        }

        public ActionResult ScheduleSummary()
        {
            if (!StaticMethods.HasAdminAccess(StaticMethods.TryParseObjToInt(Session["RoleID"])))
                return RedirectToAction("Index", "Account");

            List<ScheduleReportViewModel> model = GetScheduleSummary();

            return View(model);
        }

        #region LIST
        public List<PurchaseOrderReportViewModel> getPurchaseOrder()
        {
            List<PurchaseOrderReportViewModel> model = new List<PurchaseOrderReportViewModel>();

            var purchaseorder = unitOfWork.PurchaseOrder.GetAll();

            foreach(var item in purchaseorder)
            {
                model.Add(new PurchaseOrderReportViewModel
                {
                    PurchaseOrderID = item.PURCHASENO,
                    VendorCode = item.COMPANY != null ? item.COMPANY.CODE : string.Empty,
                    CompanyName = item.COMPANY != null ? item.COMPANY.NAME : string.Empty,
                    DateOrdered = item.DATEPURCHASED.HasValue ? item.DATEPURCHASED.Value.ToShortDateString() : string.Empty,
                    BuyerName = item.USER != null ? item.USER.FIRSTNAME + " " + item.USER.LASTNAME : string.Empty,
                    FreightCharge = "0.00",
                    SalesTax = "0.00",
                    Amount = item.AMOUNT.ToString()

                });
            }

            return model;
        }

        public List<SalesOrderReportViewModel> getSalesOrder()
        {
            List<SalesOrderReportViewModel> model = new List<SalesOrderReportViewModel>();

            var ordertrans = unitOfWork.OrderTran.GetAll();
            foreach (var item in ordertrans)
            {
                var admin = unitOfWork.User.Get(item.LASTUPDATEDBY);

                model.Add(new SalesOrderReportViewModel
                {
                    SalesOrderID = item.ORDERNO, //--> Add Last two characters of a year
                    CustomerName = item.USER.FIRSTNAME + " " + item.USER.LASTNAME,
                    CompanyName = item.USER.COMPANY != null ? item.USER.COMPANY.NAME : string.Empty,
                    DateOrdered = item.DATEORDERED.HasValue ? item.DATEORDERED.Value.ToShortDateString() : string.Empty, //--> Add DateOrdered on OrderTransactionTable
                    SalesPerson = admin.FIRSTNAME + " " + admin.LASTNAME,
                    PayCode = "NA",
                    SalesTax = "0.00",
                    Amount = item.TOTALPRICE.ToString()
                });
            };

            return model;
        }

        public List<OrderListStatementOfAccReportViewModel> GetStatementOfAccList()
        {
            List<OrderListStatementOfAccReportViewModel> model = new List<OrderListStatementOfAccReportViewModel>();

            var ordertransactions = unitOfWork.OrderTran.GetAll();

            foreach (var item in ordertransactions)
            {
                model.Add(new OrderListStatementOfAccReportViewModel
                {
                    Id = item.ID,
                    CustomerName = item.USER.FIRSTNAME + " " + item.USER.LASTNAME,
                    Company = item.USER.COMPANY_ID != 0 ? item.USER.COMPANY.NAME : string.Empty,
                    PriorityLevel = item.PRIORITYLEVEL,
                    Location = item.LOCATION,
                    Status = item.STATUS,
                    TotalPrice = item.TOTALPRICE
                });
            }

            return model;
        }

        public List<SupplierReportViewModel> GetSupplierList()
        {
            List<SupplierReportViewModel> model = new List<SupplierReportViewModel>();

            var companies = unitOfWork.Company.Find(m => m.TYPE == Constant.COMPANY_TYPE_VENDOR);
            foreach (var item in companies)
            {
                model.Add(new SupplierReportViewModel
                {
                    SupplierCode = item.CODE,
                    Name = item.NAME,
                    Address = item.ADDRESS,
                });
            }

            return model;
        }

        public List<InventoryReportViewModel> GetInventorySummary()
        {
            List<InventoryReportViewModel> model = new List<InventoryReportViewModel>();

            var inventory = unitOfWork.Inventory.GetAll();
            foreach (var item in inventory)
            {
                model.Add(new InventoryReportViewModel
                {
                    InventoryID = item.ID.ToString(),
                    Name = item.NAME,
                    Category = item.CATEGORY.NAME,
                    StockQuantity = item.QUANTITY.ToString(),
                    //ShippedQuantity = "0.00",
                    //SoldQuantity = "0.00",
                    TotalCost = (item.QUANTITY * item.PRICE).ToString()
                });
            }

            return model;
        }

        public List<ScheduleReportViewModel> GetScheduleSummary()
        {
            List<ScheduleReportViewModel> model = new List<ScheduleReportViewModel>();

            var servicetran = unitOfWork.ServiceTran.GetAll();
            foreach (var item in servicetran)
            {
                var servicesched = item.USERSERVICESCHEDS.LastOrDefault();
                model.Add(new ScheduleReportViewModel
                {
                    ID = item.ID.ToString(),
                    Name = item.SERVICE != null ? item.SERVICE.NAME : string.Empty,
                    Client = item.USER != null ? item.USER.FIRSTNAME + " " + item.USER.LASTNAME : string.Empty,
                    Company = item.USER.COMPANY != null ? item.USER.COMPANY.NAME : string.Empty,
                    Assigned = servicesched.USER != null ? servicesched.USER.FIRSTNAME + " " + servicesched.USER.LASTNAME : string.Empty,
                    DateScheduled = servicesched.DATESCHEDULED.HasValue ? servicesched.DATESCHEDULED.Value.ToLocalTime().ToShortDateString() : string.Empty,
                    Status = item.STATUS,
                });
            }

            return model;
        }
        #endregion

        //--> 1 - Purchase Order
        //--> 2 - Sales Order
        //--> 3 - Statement of Account
        //--> 4 - Supplier List
        //--> 5 - Inventory Summary
        //--> 6 - Schedule Summary
        public FileResult ExportOrder(int type, int orderId = 0)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                //StringReader sr = new StringReader("");
                DateTime dateTime = DateTime.Now;
                Document doc = new Document(PageSize.A4.Rotate());
                doc.SetMargins(10f, 10f, 10f, 10f);

                PdfWriter.GetInstance(doc, stream).CloseStream = false;
                doc.Open();

                if (type== 1)
                {
                    //Create PDF Table
                    PdfPTable tableLayout = new PdfPTable(8);

                    string[] headers = { "PO #", "Vendor Code", "Company", "Date Ordered", "Buyer", "Freight Charge", "Sales Tax", "Amount" };
                    float[] width = { 25, 50, 50, 25, 50, 25, 25, 45 };

                    List<PurchaseOrderReportViewModel> model = getPurchaseOrder();
 
                    //Add Content to PDF   
                    doc.Add(AddTableToPDF(tableLayout, headers, width, model, "Purchase Order Summary Report"));

                }
                else if (type == 2)
                {
                    //Create PDF Table
                    PdfPTable tableLayout = new PdfPTable(8);

CRM TripleTech/CRM TripleTech/Views/Reports/InventorySummary.cshtml
@model IEnumerable<CRM_TripleTech.Models.ViewModels.Report.InventoryReportViewModel>
@{
    ViewBag.Title = "Inventory Summary";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Inventory Summary Report</h4>
            </div>
            <div class="card-body">
                <div id="Grid" class="table-responsive">
                    <table id="tblMain" class="table table-hover">
                        <thead class="text-primary">
                            <tr>
                                <th style="width:auto;border: 1px solid #ccc">No</th>
                                <th style="width:auto;border: 1px solid #ccc">Name</th>
                                <th style="width:auto;border: 1px solid #ccc">Category</th>
                                <th style="width:auto;border: 1px solid #ccc">Stock Quantity</th>
                                @*<th style="width:auto;border: 1px solid #ccc">Shipped</th>
                                <th style="width:auto;border: 1px solid #ccc">Sold</th>*@
                                <th style="width:auto;border: 1px solid #ccc">Total Cost</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td style="width:auto;border: 1px solid #ccc">@item.InventoryID</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.Name</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.Category</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.StockQuantity</td>
                                    @*<td style="width:auto;border: 1px solid #ccc">@item.ShippedQuantity</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.SoldQuantity</td>*@
                                    <td style="width:auto;border: 1px solid #ccc">₱ @item.TotalCost</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <a class="btn btn-primary" href="@Url.Action("ExportOrder", "Reports", routeValues: new { @type = "5"})">Generate Report</a>
            </div>
        </div>
    </div>
</div>

CRM TripleTech/CRM TripleTech/Views/Reports/PurchaseOrder.cshtml
@model IEnumerable<CRM_TripleTech.Models.ViewModels.Report.PurchaseOrderReportViewModel>
@{
    ViewBag.Title = "Purchase Order";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Purchase Order Report</h4>
            </div>
            <div class="card-body">
                <div id="Grid" class="table-responsive">
                    <table id="tblMain" class="table table-hover">
                        <thead class="text-primary">
                            <tr>
                                <th style="width:auto;border: 1px solid #ccc">PO #</th>
                                <th style="width:auto;border: 1px solid #ccc">Vendor Code</th>
                                <th style="width:auto;border: 1px solid #ccc">Company</th>
                                <th style="width:auto;border: 1px solid #ccc">Date Ordered</th>
                                <th style="width:auto;border: 1px solid #ccc">Buyer</th>
                                <th style="width:auto;border: 1px solid #ccc">Freight Charge</th>
                                <th style="width:auto;border: 1px solid #ccc">Sales Tax</th>
                                <th style="width:auto;border: 1px solid #ccc">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td style="width:auto;border: 1px solid #ccc">@item.PurchaseOrderID</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.VendorCode</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.CompanyName</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.DateOrdered</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.BuyerName</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.FreightCharge</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.SalesTax</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.Amount</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <a class="btn btn-primary" href="@Url.Action("ExportOrder", "Reports", routeValues: new { @type = "1"})">Generate Report</a>
            </div>
        </div>
    </div>
</div>

CRM TripleTech/CRM TripleTech/Views/Reports/SalesOrder.cshtml
@model IEnumerable<CRM_TripleTech.Models.ViewModels.Report.SalesOrderReportViewModel>
@{
    ViewBag.Title = "Sales Order";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Sales Order Report</h4>
            </div>
            <div class="card-body">
                <div id="Grid" class="table-responsive">
                    <table id="tblMain" class="table table-hover">
                        <thead class="text-primary">
                            <tr>
                                <th style="width:auto;border: 1px solid #ccc">SO #</th>
                                <th style="width:auto;border: 1px solid #ccc">Customer Name</th>
                                <th style="width:auto;border: 1px solid #ccc">Company</th>
                                <th style="width:auto;border: 1px solid #ccc">Order Date</th>
                                <th style="width:auto;border: 1px solid #ccc">Sales Person</th>
                                <th style="width:auto;border: 1px solid #ccc">Pay Code</th>
                                <th style="width:auto;border: 1px solid #ccc">Sales Tax</th>
                                <th style="width:auto;border: 1px solid #ccc">Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td style="width:auto;border: 1px solid #ccc">@item.SalesOrderID</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.CustomerName</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.CompanyName</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.DateOrdered</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.SalesPerson</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.PayCode</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.SalesTax</td>
                                    <td style="width:auto;border: 1px solid #ccc">@item.Amount</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <a class="btn btn-primary" href="@Url.Action("ExportOrder", "Reports", routeValues: new { @type = "2"})">Generate Report</a>
            </div>
        </div>
    </div>
</div>

CRM TripleTech/CRM TripleTech/Views/Reports/StatementOfAccount.cshtml
@model IEnumerable<CRM_TripleTech.Models.ViewModels.Report.OrderListStatementOfAccReportViewModel>
@using CRM_TripleTech.Models
@{
    ViewBag.Title = "Statement Of Account";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title">Orders Table</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table id="tblMain" class="table table-hover">
                        <thead class="text-primary">
                            <tr>
                                <th></th>
                                <th>ID</th>
                                <th>Customer</th>
                                <th>Priority</th>
                                <th>Location</th>
                                <th>Status</th>
                                <th>Total Price</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td></td>
                                    <td><a href="@Url.Action("Details", "OrderTran", routeValues: new { @id = item.Id})">@item.Id</a></td>
                                    <td>
                                        @item.CustomerName
                                        <br />
                                        <small>@item.Company</small>
                                    </td>
                                    <td>
                                        @if (item.PriorityLevel == Constant.PRIORITY_LEVEL_HIGH)
                                        {<span class="text-danger">@item.PriorityLevel</span> }
                                        else if (item.PriorityLevel == Constant.PRIORITY_LEVEL_MED)
                                        { <span class="text-warning">@item.PriorityLevel</span> }
                                        else
                                        { <span class="text-success">@item.PriorityLevel</span>}
                                    </td>
                                    <td>@item.Location</td>
                                    <td>
                                        @if (item.Status == Constant.ORDERTRAN_STATUS_ACTIVE)
                                        {<span class="badge badge-pill badge-secondary">@item.Status</span> }
                                        else if (item.Status == Constant.ORDERTRAN_STATUS_PROCESSING)
                                        { <span class="badge badge-pill badge-info">@item.Status</span> }
                                        else if (item.Status == Constant.ORDERTRAN_STATUS_SHIPPING)
                                        { <span class="badge badge-pill badge-info">@item.Status</span>}
                                        else if (item.Status == Constant.ORDERTRAN_STATUS_COMPLETED)
                                        { <span class="badge badge-pill badge-success">@item.Status</span>}
                                        else if (item.Status == Constant.ORDERTRAN_STATUS_CANCELLED)
                                        { <span class="badge badge-pill badge-danger">@item.Status</span>}
                                    </td>
                                    <td>₱ @item.TotalPrice</td>
                                    <td><a class="btn btn-primary" href="@Url.Action("ExportOrder", "Reports", routeValues: new { @type = "3", @orderId = item.Id})">Generate SOA</a></td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $('#tblMain').DataTable({
                'paging': true,
                'lengthChange': false,
                'searching': false,
                'ordering': true,
                'info': false,
                'autoWidth': true
            });
        });</script>
}